name: Compile Flutter Android App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with: {java-version: '17', distribution: 'temurin'}

    # This installs Flutter onto the cloud runner
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    # Downloads packages and auto-generates the local.properties file
    - name: Install Dependencies
      working-directory: ./physio_app
      run: flutter pub get

    # Compiles the clean Android APK using Flutter's native pipeline
        # Compiles the Android APK bypassing the version check
    - name: Build APK
      working-directory: ./physio_app
      run: flutter build apk --debug --android-skip-build-dependency-validation

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: my-flutter-android-app
        path: physio_app/build/app/outputs/flutter-apk/app-debug.apk
